apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-serving
  namespace: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-serving
  template:
    metadata:
      labels:
        app: fraud-serving
    spec:
      containers:
        - name: api
          image: docker.io/thiagoar587/fraud-serve:latest
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-svc:5000"
            - name: MODEL_URI
              value: "models:/fraud-xgb@champion"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: mlflow-vol
              mountPath: /mlflow
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: mlflow-vol
          persistentVolumeClaim:
            claimName: mlflow-pvc
