apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: fraud-detection
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi                # 20 GB para o CSV de 1M de linhas