FROM python:3.11-slim-bookworm@sha256:8404ed8464ae7275b5c13a00c6edd2e027c6560a1f74bd4c7dee39f5d00f9352
WORKDIR /mlflow

RUN pip install --no-cache-dir mlflow==2.14.3

EXPOSE 5000
CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////mlflow/mlflow.db", \
     "--default-artifact-root", "/mlflow/artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000"]
